"""add result ai_icebreaker column

Revision ID: 3d2ac650b29c
Revises: 26520f75246a
Create Date: 2026-10-06 18:49:26.709395

Adds `ai_icebreaker` (String 1000, nullable=True) to results table.
Stores personalized email snippets generated by Anthropic API.

Run against the app DB only: `alembic -x target=app upgrade app@head`.
"""

import sqlalchemy as sa
from alembic import op

revision = "3d2ac650b29c"
down_revision = "26520f75246a"
branch_labels = None
depends_on = None


def upgrade() -> None:
    op.add_column("results", sa.Column("ai_icebreaker", sa.String(1000), nullable=True))


def downgrade() -> None:
    op.drop_column("results", "ai_icebreaker")
